plugin:
    name: 'yamobile.services::lang.plugin.name'
    description: 'yamobile.services::lang.plugin.description'
    author: 'yamobile.services::lang.plugin.author'
    icon: icon-folder
    homepage: 'https://github.com/ya-mobile-ru/oc-services-plugin'
navigation:
    services-menu:
        label: 'yamobile.services::lang.navigation.service_menu'
        url: yamobile/services/services
        icon: icon-folder
        sideMenu:
            side-menu-services:
                label: 'yamobile.services::lang.navigation.side_menu_services'
                url: yamobile/services/services
                icon: icon-sitemap
            side-menu-subservices:
                label: 'yamobile.services::lang.navigation.side_menu_subservices'
                url: yamobile/services/subservices
                icon: icon-list
