title: Services
modelClass: Yamobile\Services\Models\Service
list: $/yamobile/services/models/service/columns.yaml
recordUrl: 'yamobile/services/services/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
