name: Subservices
modelClass: Yamobile\Services\Models\Subservice
form: $/yamobile/services/models/subservice/fields.yaml
defaultRedirect: yamobile/services/subservices
create:
    redirect: 'yamobile/services/subservices/update/:id'
    redirectClose: yamobile/services/subservices
update:
    redirect: yamobile/services/subservices
    redirectClose: yamobile/services/subservices
preview: {  }
