list: $/yamobile/services/models/subservice/columns.yaml
modelClass: Yamobile\Services\Models\Subservice
title: Subservices
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'yamobile/services/subservices/update/:id'
