title: Subservices
modelClass: Yamobile\Services\Models\Subservice
list: $/yamobile/services/models/subservice/columns.yaml
recordUrl: 'yamobile/services/subservices/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
